server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defautlZone: http://${eureka.instance.hostname}:${server.port}/eureka/
